name: hello-world

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check_out_repository_code
        uses: actions/checkout@v3
        
      - name: say_hello
        run: make say_hello
        
